[package]
name = "belt-dwp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hex-literal = "0.4.1"
ghash = "0.5.1"
belt-block = "0.1.2"